#!/bin/bash

#STORAGE ACCOUNT DETAILS - THIS CAN BE FOUND IN THE OUTPUTS OF THE azuredeploy-queue ARM TEMPLATE DEPLOYMENT
STORAGE_ACC_KEY=<INSERT_STORAGE_KEY_HERE>
STORAGE_ACC_NAME=<INSERT_STORAGE_ACC_NAME_HERE>
#RESOURCE GROUP NAME 
RESOURCE_GROUP=<INSERT_RG_NAME_HERE>
#SCALE_SET_NAME - THIS CAN BE FOUND IN THE AZURE PORTAL
SCALE_SET_NAME=<INSERT_SCALE_SET_NAME_HERE>


#PARAMETERS BELOW THIS LINE CAN STAY UNCHANGED
QUEUE_NAME=twtqueue


